export const quron = [
    {
        id: '123',
        name: "Mishary Alafasi",
        Server: "https://server8.mp3quran.net/afs",
        rewaya: "Rewayat Hafs A'n Assem",
        count: "114",
        letter: 'M',
        suras:
      "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114",
    
    }
    
];

console.log(quron[0].Server);

export const name = [
    { id: 1, uz: "Al-Fatiha", arabic: "ٱلْفَاتِحَة" },
    { id: 2, uz: "Al-Baqarah", arabic: "ٱلْبَقَرَة" },
    { id: 3, uz: "Al Imran", arabic: "آلِ عِمْرَان" },
    { id: 4, uz: "An-Nisa", arabic: "ٱلنِّسَاء" },
    { id: 5, uz: `Al-Ma'idah`, arabic: "ٱلْمَائِدَة" },
    { id: 6, uz: `Al-An'am`, arabic: "ٱلْأَنْعَام" },
    { id: 7, uz: `Al-A'raf`, arabic: "ٱلْأَعْرَاف" },
    { id: 8, uz: "Al-Anfal", arabic: "ٱلْأَنْفَال" },
    { id: 9, uz: "	At-Tawbah", arabic: "ٱلتَّوْبَة" },
    { id: 10, uz: "Yunus", arabic: "يُونُس" },
    { id: 11, uz: "	Hud", arabic: "هُود" },
    { id: 12, uz: "Yusuf", arabic: "	يُوسُف" },
    { id: 13, uz: `Ar-Ra'd`, arabic: "ٱلرَّعْد" },
    { id: 14, uz: "Ibrahim", arabic: "إِبْرَاهِيم" },
    { id: 15, uz: "Al-Hijr", arabic: "	ٱلْحِجْر" },
    { id: 16, uz: "	An-Nahl", arabic: "ٱلنَّحْل" },
    { id: 17, uz: "Al-Isra", arabic: "ٱلْإِسْرَاء" },
    { id: 18, uz: "Al-Kahf", arabic: "ٱلْكَهْف" },
    { id: 19, uz: "Maryam", arabic: "	مَرْيَم" },
    { id: 20, uz: "	Ta-Ha", arabic: "طه" },
    { id: 21, uz: "	Al-Anbiya", arabic: "ٱلْأَنْبِيَاء" },
    { id: 22, uz: "	Al-Hajj", arabic: "ٱلْحَجّ" },
    { id: 23, uz: "Al-Mu'minun", arabic: "	ٱلْمُؤْمِنُون" },
    { id: 24, uz: "An-Nur", arabic: "ٱلنُّور" },
    { id: 25, uz: "	Al-Furqan", arabic: "ٱلْفُرْقَان" },
    { id: 26, uz: "Ash-Shu'ara", arabic: "ٱلشُّعَرَاء" },
    { id: 27, uz: "An-Naml", arabic: "ٱلنَّمْل" },
    { id: 28, uz: "	Al-Qasas", arabic: "ٱلْقَصَص " },
    { id: 29, uz: "Al-Ankabut", arabic: "ٱلْعَنْكَبُوت" },
    { id: 30, uz: "Ar-Rum", arabic: "ٱلرُّوم" },
    { id: 31, uz: "Luqmaan", arabic: "	لُقْمَان" },
    { id: 32, uz: "As-Sajda", arabic: "ٱلسَّجْدَة" },
    { id: 33, uz: "Al-Ahzaab", arabic: "ٱلْأَحْزَاب" },
    { id: 34, uz: "Saba'", arabic: "سَبَأ" },
    { id: 35, uz: "Faatir", arabic: "فَاطِر" },
    { id: 36, uz: "Ya Sin", arabic: "يس" },
    { id: 37, uz: "	As-Saaffaat", arabic: "ٱلصَّافَّات" },
    { id: 38, uz: "Saad", arabic: "ص" },
    { id: 39, uz: "Az-Zumar", arabic: "ٱلزُّمَر" },
    { id: 40, uz: "	Ghafir", arabic: "غَافِر" },
    { id: 41, uz: "Fussilat", arabic: "فُصِّلَت" },
    { id: 42, uz: "Ash_Shooraa", arabic: "ٱلشُّورىٰ" },
    { id: 43, uz: "Az-Zukhruf", arabic: "ٱلْزُّخْرُف" },
    { id: 44, uz: "Ad-Dukhaan", arabic: "ٱلدُّخَان" },
    { id: 45, uz: "	Al-Jaathiyah", arabic: "ٱلْجَاثِيَة" },
    { id: 46, uz: "	Al-Ahqaaf", arabic: "ٱلْأَحْقَاف" },
    { id: 47, uz: "Muhammad", arabic: "مُحَمَّد" },
    { id: 48, uz: "	Al-Fath", arabic: "ٱلْفَتْح" },
    { id: 49, uz: "Al-Hujuraat", arabic: "ٱلْحُجُرَات" },
    { id: 50, uz: "Qaaf", arabic: "ق" },
    { id: 51, uz: "Adh-Dhaariyaat", arabic: "ٱلذَّارِيَات" },
    { id: 52, uz: "At-Toor", arabic: "ٱلطُّور" },
    { id: 53, uz: "An-Najm", arabic: "ٱلنَّجْم" },
    { id: 54, uz: "Al-Qamar", arabic: "ٱلْقَمَر" },
    { id: 55, uz: "Ar-Rahman", arabic: "ٱلرَّحْمَٰن" },
    { id: 56, uz: "	Al-Waqi'a", arabic: "ٱلْوَاقِعَة" },
    { id: 57, uz: "	Al-Hadeed", arabic: "ٱلْحَدِيد" },
    { id: 58, uz: "	Al-Mujadila", arabic: "ٱلْمُجَادِلَة" },
    { id: 59, uz: "Al-Hashr", arabic: "ٱلْحَشْر" },
    { id: 60, uz: "Al-Mumtahanah", arabic: "ٱلْمُمْتَحَنَة" },
    { id: 61, uz: "As-Saff", arabic: "ٱلصَّفّ" },
    { id: 62, uz: "Al-Jumu'ah", arabic: "ٱلْجُمُعَة" },
    { id: 63, uz: "Al-Munafiqoon", arabic: "ٱلْمُنَافِقُون" },
    { id: 64, uz: "At-Taghabun", arabic: "ٱلتَّغَابُن" },
    { id: 65, uz: "At-Talaq", arabic: "ٱلطَّلَاق" },
    { id: 66, uz: "At-Tahreem", arabic: "ٱلتَّحْرِيم" },
    { id: 67, uz: "	Al-Mulk", arabic: "ٱلْمُلْك" },
    { id: 68, uz: "	Al-Qalam", arabic: "ٱلْقَلَم" },
    { id: 69, uz: "Al-Haaqqa", arabic: "ٱلْحَاقَّة" },
    { id: 70, uz: "Al-Ma'aarij", arabic: "ٱلْمَعَارِج" },
    { id: 71, uz: "	Nuh", arabic: "نُوح" },
    { id: 72, uz: "	Al-Jinn", arabic: "ٱلْجِنّ" },
    { id: 73, uz: "	Al-Muzzammil", arabic: "ٱلْمُزَّمِّل" },
    { id: 74, uz: "Al-Muddaththir", arabic: "ٱلْمُدَّثِّر" },
    { id: 75, uz: "Al-Qiyamah", arabic: "ٱلْقِيَامَة" },
    { id: 76, uz: "Al-Insaan", arabic: "ٱلْإِنْسَان" },
    { id: 77, uz: "Al-Mursalaat", arabic: "" },
    { id: 78, uz: `An-Naba'`, arabic: "ٱلنَّبَأ" },
    { id: 79, uz: "	An-Naazi'aat", arabic: "ٱلنَّازِعَات" },
    { id: 80, uz: "Abasa", arabic: "عَبَسَ" },
    { id: 81, uz: "At-Takvir", arabic: "ٱلتَّكْوِير" },
    { id: 82, uz: "Al-Infitar", arabic: "ٱلْإِنْفِطَار" },
    { id: 83, uz: "Al-Mutaffifeen", arabic: "ٱلْمُطَفِّفِين" },
    { id: 84, uz: "Al-Inshiqaaq", arabic: "ٱلْإِنْشِقَاق" },
    { id: 85, uz: "Al-Burooj", arabic: "ٱلْبُرُوج" },
    { id: 86, uz: "At-Taariq", arabic: "ٱلطَّارِق" },
    { id: 87, uz: "Al-A'laa", arabic: "ٱلْأَعْلَىٰ" },
    { id: 88, uz: "Al-Ghaashiyah", arabic: "ٱلْغَاشِيَة" },
    { id: 89, uz: "Al-Fajr", arabic: "ٱلْفَجْر" },
    { id: 90, uz: "Al-Balad", arabic: "ٱلْبَلَد" },
    { id: 91, uz: "Ash-Shams", arabic: "ٱلشَّمْس" },
    { id: 92, uz: "Al-Layl", arabic: "ٱللَّيْل" },
    { id: 93, uz: "Ad-Dhuha", arabic: "ٱلضُّحَىٰ" },
    { id: 94, uz: "Ash-Sharh", arabic: "ٱلشَّرْح" },
    { id: 95, uz: "At-Tiyn", arabic: "ٱلْعَلَق" },
    { id: 96, uz: "Al-Alaq", arabic: "ٱلْعَلَق" },
    { id: 97, uz: "Al-Qadr", arabic: "ٱلْقَدْر" },
    { id: 98, uz: "Al-Bayyinahh", arabic: "ٱلْبَيِّنَة" },
    { id: 99, uz: "	Az-Zalzalah", arabic: "ٱلزَّلْزَلَة" },
    { id: 100, uz: "Al-'Aadiyaat", arabic: "ٱلْعَادِيَات" },
    { id: 101, uz: "Al-Qaari'ah", arabic: "ٱلْقَارِعَة" },
    { id: 102, uz: "At-Takaathur", arabic: "ٱلتَّكَاثُر" },
    { id: 103, uz: "Al-'Asr", arabic: "ٱلْعَصْر" },
    { id: 104, uz: "Al-Humazah", arabic: "ٱلْهُمَزَة" },
    { id: 105, uz: "Al-Fiyl", arabic: "ٱلْفِيل" },
    { id: 106, uz: "	Quraysh", arabic: "قُرَيْش" },
    { id: 107, uz: "Al-Maa'oon", arabic: "ٱلْمَاعُون" },
    { id: 108, uz: "Al-Kawthar", arabic: "ٱلْكَوْثَر" },
    { id: 109, uz: "Al-Kaafiroon", arabic: "ٱلْكَافِرُون" },
    { id: 110, uz: "An-Nasr", arabic: "ٱلنَّصْر" },
    { id: 111, uz: "Al-Masad", arabic: "ٱلْمَسَد" },
    { id: 112, uz: "Al-Ikhlaas", arabic: "ٱلْإِخْلَاص" },
    { id: 113, uz: "	Al-Falaq", arabic: "ٱلْفَلَق" },
    { id: 114, uz: "Al-Naas", arabic: "ٱلنَّاس" },
]